/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-31 15:23:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.book;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homeTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685707379948L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.0.0-beta3/css/all.min.css\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/homeTest.css\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"wrap\">\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- @@@@ 메인 비디오 @@@@  -->\n");
      out.write("		<div class=\"movieDiv\">\n");
      out.write("			<div class=\"musicSoundOn\" id=\"musicSoundOn\">\n");
      out.write("				<img src=\"/resources/img/sound_on.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"musicSoundOff\" id=\"musicSoundOff\">\n");
      out.write("				<img src=\"/resources/img/sound_off.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<img src=\"/resources/img/나의히어로아카데미아_logo.png\">\n");
      out.write("			</div>\n");
      out.write("			<video id=\"mainVideo\" autoplay loop muted>\n");
      out.write("				<source src=\"/resources/img/나의히어로아카데미아.mp4\" id=\"mainMovie\">\n");
      out.write("			</video>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"movieDiv\">\n");
      out.write("			<div class=\"musicSoundOn\" id=\"musicSoundOn\">\n");
      out.write("				<img src=\"/resources/img/sound_on.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"musicSoundOff\" id=\"musicSoundOff\">\n");
      out.write("				<img src=\"/resources/img/sound_off.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<img src=\"/resources/img/최애의아이_logo.png\">\n");
      out.write("			</div>\n");
      out.write("			<video id=\"mainVideo\" autoplay loop muted>\n");
      out.write("				<source src=\"/resources/img/최애의아이.mp4\" id=\"mainMovie\">\n");
      out.write("			</video>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"movieDiv\">\n");
      out.write("			<div class=\"musicSoundOn\" id=\"musicSoundOn\">\n");
      out.write("				<img src=\"/resources/img/sound_on.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"musicSoundOff\" id=\"musicSoundOff\">\n");
      out.write("				<img src=\"/resources/img/sound_off.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<img src=\"/resources/img/주술회전_logo.png\">\n");
      out.write("			</div>\n");
      out.write("			<video id=\"mainVideo\" autoplay loop muted>\n");
      out.write("				<source src=\"/resources/img/주술회전.mp4\" id=\"mainMovie\">\n");
      out.write("			</video>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"movieDiv\">\n");
      out.write("			<div class=\"musicSoundOn\" id=\"musicSoundOn\">\n");
      out.write("				<img src=\"/resources/img/sound_on.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"musicSoundOff\" id=\"musicSoundOff\">\n");
      out.write("				<img src=\"/resources/img/sound_off.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<img src=\"/resources/img/헌터헌터_logo.png\">\n");
      out.write("			</div>\n");
      out.write("			<video id=\"mainVideo\" autoplay loop muted>\n");
      out.write("				<source src=\"/resources/img/헌터헌터.mp4\" id=\"mainMovie\">\n");
      out.write("			</video>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"movieDiv\">\n");
      out.write("			<div class=\"musicSoundOn\" id=\"musicSoundOn\">\n");
      out.write("				<img src=\"/resources/img/sound_on.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"musicSoundOff\" id=\"musicSoundOff\">\n");
      out.write("				<img src=\"/resources/img/sound_off.png\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"logo\">\n");
      out.write("				<img src=\"/resources/img/나루토_logo.png\">\n");
      out.write("			</div>\n");
      out.write("			<video id=\"mainVideo\" autoplay loop muted>\n");
      out.write("				<source src=\"/resources/img/나루토.mp4\" id=\"mainMovie\">\n");
      out.write("			</video>\n");
      out.write("		</div>\n");
      out.write("		<a class=\"slideButton prevButton\" onclick=\"prevSlide()\"><i\n");
      out.write("			class=\"fa-solid fa-chevron-left\" style=\"color: #cccccc;\"></i></a> <a\n");
      out.write("			class=\"slideButton nextButton\" onclick=\"nextSlide()\"><i\n");
      out.write("			class=\"fa-solid fa-chevron-right\" style=\"color: #cccccc;\"></i></a> <br>\n");
      out.write("		<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- @@@@ 신작 슬라이드 @@@@ -->\n");
      out.write("		<div class=\"homeContent\">\n");
      out.write("			<div class=\"newBook\">\n");
      out.write("				<span>2023년 7월 신작</span>\n");
      out.write("				<div class=\"slideNewBook\">\n");
      out.write("					<i class=\"fa-solid fa-chevron-left slidePrevBtn\" onclick=\"prevNewSlide()\"></i>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"원피스\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/31698/75/cover500/k602833586_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>원피스 105</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"스킵과 로퍼\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32062/98/cover500/k512834890_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>스킵과 로퍼 6</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"최애의 아이\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32129/23/cover500/k902834308_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>최애의 아이 11</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"나의 히어로 아카데미아\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32094/5/cover500/k962834900_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>나의 히어로 아카데미아 38</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"환괴지대\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32143/57/cover500/k592834110_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>환괴지대 에테르의 마을</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"스파이 패밀리\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32135/16/cover500/k292834306_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>스파이 패밀리 11</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"마슐\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/31937/39/cover500/k682833055_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>마슐 14</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"도쿄리벤저스\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32129/61/cover500/k032834309_1.jpg\">\n");
      out.write("							<br>\n");
      out.write("							<p>도쿄 리벤저스 31</p>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"slideBox\">\n");
      out.write("							<img alt=\"위치 워치\"\n");
      out.write("								src=\"https://image.aladin.co.kr/product/32157/86/cover500/k502834418_1.jpg\">\n");
      out.write("							<br> <p>위치 워치 8</p>\n");
      out.write("						</div>\n");
      out.write("					<i class=\"fa-solid fa-chevron-right slideNextBtn\" onclick=\"nextNewSlide()\"></i>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		<br> <br>\n");
      out.write("\n");
      out.write("		<P>TEST</P>\n");
      out.write("\n");
      out.write("		<a href=\"/book/ProdcutDetail?bno=31\"> <img class=\"mainPic\"\n");
      out.write("			alt=\"사진 없다.\" src=\"/resources/img/1.jpg\"></a>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/home.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/book/homeTest.jsp(169,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.id != null && ses.id eq 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<a href=\"/book/register\"><button>상품등록</button></a>\n");
          out.write("			<a href=\"/book/list\"><button>상품리스트</button></a>\n");
          out.write("			<a href=\"/member/admin\"><button>관리자페이지</button></a>\n");
          out.write("			<a href=\"/review/list\">리스트뽑기</a>\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
