/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-05 11:33:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bookorder;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:replace", org.apache.taglibs.standard.functions.Functions.class, "replace", new Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685707379948L));
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>주문 상세 페이지</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("   href=\"/resources/css/Orderdetail.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("   <div class=\"orderDetailMain\">\n");
      out.write("      <div class=\"orderDetailContent\">\n");
      out.write("\n");
      out.write("         <div class=\"profileNav\">\n");
      out.write("\n");
      out.write("            <div class=\"profileArea\">\n");
      out.write("               <div class=\"ProfileImg\">\n");
      out.write("                  <img alt=\"없음\" id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uivo.uuid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                     src=\"/upload/userProfile/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn: replace(ses.uivo.saveDir, '\\\\','/')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uivo.uuid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('_');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uivo.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                     class=\"userImg\">\n");
      out.write("               </div>\n");
      out.write("               <div class=\"userNickName\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"profileNavArea\">\n");
      out.write("               <ul>\n");
      out.write("                  <li><a href=\"/member/info?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\n");
      out.write("                        class=\"material-symbols-outlined userInfo\"> person </span> 정보보기\n");
      out.write("                  </a></li>\n");
      out.write("\n");
      out.write("                  <li><a href=\"/member/modify?");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <span\n");
      out.write("                        class=\"material-symbols-outlined userInfoEdit\">\n");
      out.write("                           edit_square </span> 정보수정\n");
      out.write("                  </a></li>\n");
      out.write("                  <li><a href=\"/favorite/list\"> <span\n");
      out.write("                        class=\"material-symbols-outlined userWishList\">\n");
      out.write("                           heart_plus </span> 찜목록\n");
      out.write("                  </a></li>\n");
      out.write("                  <li><a href=\"/bookorder/User_orderlist\"> <span\n");
      out.write("                        class=\"material-symbols-outlined userBookOrder\">\n");
      out.write("                           receipt_long </span> 주문목록\n");
      out.write("                  </a></li>\n");
      out.write("                  <li><a href=\"/member/delete\"> <span\n");
      out.write("                        class=\"material-symbols-outlined userWithdrawal\">\n");
      out.write("                           heart_broken </span> 회원탈퇴\n");
      out.write("                  </a></li>\n");
      out.write("               </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("         <div class=\"orderDetailBox\">\n");
      out.write("            <div class=\"orderDetailText\">\n");
      out.write("               <p class=\"detailText\">주문 상세 내역</p>\n");
      out.write("               <hr class=\"detailLine\">\n");
      out.write("               <div class=\"userOrderDetail\">\n");
      out.write("                  <table class=\"table orderDeatilTable\">\n");
      out.write("                     <thead>\n");
      out.write("                        <tr align=\"center\">\n");
      out.write("                           <th scope=\"col\"></th>\n");
      out.write("                           <th scope=\"col\">상품명</th>\n");
      out.write("                           <th scope=\"col\">가격</th>\n");
      out.write("                           <th scope=\"col\">수량</th>\n");
      out.write("                        </tr>\n");
      out.write("                     </thead>\n");
      out.write("                     <tbody>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        <tr align=\"center\">\n");
      out.write("                           <th colspan=\"3\"></th>\n");
      out.write("                           <th>합계 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("원</th>\n");
      out.write("                        </tr>\n");
      out.write("                     </tbody>\n");
      out.write("                  </table>\n");
      out.write("               </div>\n");
      out.write("               <br> <br>\n");
      out.write("               <table class=\"table orderDetailInfo\">\n");
      out.write("                  <thead>\n");
      out.write("                     <tr align=\"center\">\n");
      out.write("                        <th scope=\"col\">주문번호</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.ono }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <th scope=\"col\">주문일자</th>\n");
      out.write("                        ");
      if (_jspx_meth_fmt_005fparseDate_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr align=\"center\">\n");
      out.write("                        <th scope=\"col\">주문하신 분</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.uvo.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <th scope=\"col\">받으시는 분</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr align=\"center\">\n");
      out.write("                        <th scope=\"col\">주문상태</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.orderStatus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                        <th scope=\"col\">결제방법</th>\n");
      out.write("                        <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.payType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr align=\"center\">\n");
      out.write("                        <th scope=\"col\">배송지 주소</th>\n");
      out.write("                        <td colspan=\"3\">(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\n");
      out.write("                           ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressJuso}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr align=\"center\">\n");
      out.write("                        <th scope=\"col\">요청사항</th>\n");
      out.write("                        <td colspan=\"3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.etc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("                     </tr>\n");
      out.write("                  </thead>\n");
      out.write("               </table>\n");
      out.write("               <div class=\"btnBox\">\n");
      out.write("                  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("               </div>\n");
      out.write("               <!-- Button trigger modal -->\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("   <!-- orderDetailText 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\n");
      out.write("   \n");
      out.write("\n");
      out.write("   <!-- Modal 1 -->\n");
      out.write("   <div class=\"modal fade\" id=\"confirm\" tabindex=\"-1\"\n");
      out.write("      aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("         <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("               <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("                  aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\" align=\"center\">주문을 취소하시겠습니까?</div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("               <a href=\"/bookorder/cancle?ono=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.ono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button\n");
      out.write("                     type=\"button\" class=\"yesBtn\">예</button></a>\n");
      out.write("               <button type=\"button\" class=\"noBtn\" data-bs-dismiss=\"modal\">아니오</button>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <!-- Modal 1 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <!-- Modal 2 -->\n");
      out.write("   <div class=\"modal fade\" id=\"modify\" tabindex=\"-1\"\n");
      out.write("      aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("         <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("               <h5 class=\"modal-title\">배송정보수정</h5>\n");
      out.write("               <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("                  aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("            <form action=\"/bookorder/modify\" method=\"post\">\n");
      out.write("               <div class=\"modal-body\">\n");
      out.write("               \n");
      out.write("                  <input type=\"hidden\" name=\"ono\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.ono}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                  \n");
      out.write("                  <div class=\"recipientName\">\n");
      out.write("                  <span>받는분 성함</span> \n");
      out.write("                  <input type=\"text\" name=\"name\"\n");
      out.write("                   value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"recipientNameInput\"><br> \n");
      out.write("                  </div>\n");
      out.write("                     \n");
      out.write("                     \n");
      out.write("                   <div class=\"postCode\">\n");
      out.write("                    <span>우편번호</span>\n");
      out.write("                  <input type=\"text\" id=\"sample4_postcode\" placeholder=\"우편번호\"\n");
      out.write("                     name=\"addressCode\" class=\"postCodeInput\" \n");
      out.write("                     value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\n");
      out.write("                  <input type=\"button\" onclick=\"sample4_execDaumPostcode()\"\n");
      out.write("                     value=\"우편번호 찾기\" class=\"findPostCode\">\n");
      out.write("                   </div>  \n");
      out.write("                  \n");
      out.write("                  \n");
      out.write("                  \n");
      out.write("                  <div class=\"roadAddress\">\n");
      out.write("                    <span>도로명주소</span>\n");
      out.write("                     <input type=\"text\" id=\"sample4_roadAddress\" \n");
      out.write("                     placeholder=\"도로명주소\" class=\"roadAddressInput\"\n");
      out.write("                     name=\"addressJuso\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressJuso}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("                     readonly>\n");
      out.write("                  </div>\n");
      out.write("                  \n");
      out.write("                  \n");
      out.write("                  <div class=\"landAddress\">\n");
      out.write("                  \n");
      out.write("                  <span>지번주소</span>\n");
      out.write("                  <input type=\"text\" id=\"sample4_jibunAddress\"\n");
      out.write("                     placeholder=\"지번주소\" readonly class=\"landAddressInput\"><br>\n");
      out.write("                      <span id=\"guide\"\n");
      out.write("                     style=\"color: #999; display: none\"></span>\n");
      out.write("                     \n");
      out.write("                  </div>\n");
      out.write("                     \n");
      out.write("                   <div class=\"detailAddress\">\n");
      out.write("                   <span>상세주소</span>\n");
      out.write("                \n");
      out.write("                     <input\n");
      out.write("                      type=\"text\" id=\"sample4_detailAddress\" class=\"detailAddressInput\"\n");
      out.write("                      placeholder=\"상세주소\" name=\"addressDetail\" \n");
      out.write("                      value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.addressDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                   </div> \n");
      out.write("                   \n");
      out.write("                   <div class=\"deliveryRequest\">\n");
      out.write("                   <p>요청사항</p>\n");
      out.write("                  <textarea rows=\"10\" cols=\"55\" name=\"etc\" style=\"resize: none\"\n");
      out.write("                  class=\"deliveryRequestInput\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.etc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\n");
      out.write("                   </div>\n");
      out.write("             \n");
      out.write("             \n");
      out.write("               </div>\n");
      out.write("               \n");
      out.write("               \n");
      out.write("               \n");
      out.write("               <div class=\"modal-footer\">\n");
      out.write("                  <button type=\"button\" class=\"modalNo\" data-bs-dismiss=\"modal\">취소하기</button>\n");
      out.write("                  <button type=\"submit\" class=\"modalOk\">수정완료</button>\n");
      out.write("               </div>\n");
      out.write("            </form>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("   <!-- Modal 2 modal fade  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("   <script\n");
      out.write("      src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("   <script>\n");
      out.write("      //본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\n");
      out.write("      function sample4_execDaumPostcode() {\n");
      out.write("         new daum.Postcode(\n");
      out.write("               {\n");
      out.write("                  oncomplete : function(data) {\n");
      out.write("                     // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("                     // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\n");
      out.write("                     // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("                     var roadAddr = data.roadAddress; // 도로명 주소 변수\n");
      out.write("                     var extraRoadAddr = ''; // 참고 항목 변수\n");
      out.write("\n");
      out.write("                     // 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("                     // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("                     if (data.bname !== ''\n");
      out.write("                           && /[동|로|가]$/g.test(data.bname)) {\n");
      out.write("                        extraRoadAddr += data.bname;\n");
      out.write("                     }\n");
      out.write("                     // 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("                     if (data.buildingName !== ''\n");
      out.write("                           && data.apartment === 'Y') {\n");
      out.write("                        extraRoadAddr += (extraRoadAddr !== '' ? ', '\n");
      out.write("                              + data.buildingName : data.buildingName);\n");
      out.write("                     }\n");
      out.write("                     // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("                     if (extraRoadAddr !== '') {\n");
      out.write("                        extraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("                     }\n");
      out.write("\n");
      out.write("                     // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("                     document.getElementById('sample4_postcode').value = data.zonecode;\n");
      out.write("                     document.getElementById(\"sample4_roadAddress\").value = roadAddr;\n");
      out.write("                     document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\n");
      out.write("\n");
      out.write("                     var guideTextBox = document.getElementById(\"guide\");\n");
      out.write("                     // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\n");
      out.write("                     if (data.autoRoadAddress) {\n");
      out.write("                        var expRoadAddr = data.autoRoadAddress\n");
      out.write("                              + extraRoadAddr;\n");
      out.write("                        guideTextBox.innerHTML = '(예상 도로명 주소 : '\n");
      out.write("                              + expRoadAddr + ')';\n");
      out.write("                        guideTextBox.style.display = 'block';\n");
      out.write("\n");
      out.write("                     } else if (data.autoJibunAddress) {\n");
      out.write("                        var expJibunAddr = data.autoJibunAddress;\n");
      out.write("                        guideTextBox.innerHTML = '(예상 지번 주소 : '\n");
      out.write("                              + expJibunAddr + ')';\n");
      out.write("                        guideTextBox.style.display = 'block';\n");
      out.write("                     } else {\n");
      out.write("                        guideTextBox.innerHTML = '';\n");
      out.write("                        guideTextBox.style.display = 'none';\n");
      out.write("                     }\n");
      out.write("                  }\n");
      out.write("               }).open();\n");
      out.write("      }\n");
      out.write("   </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/bookorder/orderdetail.jsp(75,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/bookorder/orderdetail.jsp(75,24) '${bodto.boidto}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bodto.boidto}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/bookorder/orderdetail.jsp(75,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("items");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                           <tr align=\"center\">\n");
            out.write("                              <td><a href=\"/book/ProductDetail?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.boivo.bno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><img class=\"orderDetailImg\" alt=\"사진없음\"\n");
            out.write("                                 src=\"/upload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn: replace(items.bivo.saveDir, '\\\\','/')}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.bivo.uuid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('_');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.bivo.fileName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></a></td>\n");
            out.write("                              <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.boivo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                              <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.boivo.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                              <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${items.boivo.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                           </tr>\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fparseDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:parseDate
    org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag _jspx_th_fmt_005fparseDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag) _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag.class);
    boolean _jspx_th_fmt_005fparseDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fparseDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fparseDate_005f0.setParent(null);
      // /WEB-INF/views/bookorder/orderdetail.jsp(98,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseDate_005f0.setVar("parsedate");
      // /WEB-INF/views/bookorder/orderdetail.jsp(98,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseDate_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.orderDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/bookorder/orderdetail.jsp(98,24) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fparseDate_005f0 = _jspx_th_fmt_005fparseDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fparseDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fparseDate_005f0);
      _jspx_th_fmt_005fparseDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparseDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fparseDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/bookorder/orderdetail.jsp(100,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setVar("orderdate");
      // /WEB-INF/views/bookorder/orderdetail.jsp(100,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${parsedate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/bookorder/orderdetail.jsp(100,24) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/bookorder/orderdetail.jsp(128,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodto.bovo.orderStatus eq '결제완료'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                     <div class=\"btnDiv\" align=\"center\">\n");
          out.write("                        <button type=\"button\" class=\"orderDetailcancelBtn\"\n");
          out.write("                           data-bs-toggle=\"modal\" data-bs-target=\"#confirm\">주문취소</button>\n");
          out.write("                        <button type=\"button\" class=\"orderDetailmodifyBtn\"\n");
          out.write("                           data-bs-toggle=\"modal\" data-bs-target=\"#modify\">배송정보수정</button>\n");
          out.write("                     </div>\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
