/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-09 11:06:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../resources/user_join.css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"wrap\"> <!--전체를 둘러싸는 디브-->\n");
      out.write("\n");
      out.write("<form action=\"/member/signup\" method=\"post\">\n");
      out.write("<!--================ id =====================  -->\n");
      out.write("<div class=\"Div\"> <!--id div  -->\n");
      out.write("\n");
      out.write("<div class=\"Text\"> <!--id text div  -->\n");
      out.write("아이디\n");
      out.write("</div> <!--id text div 끝  -->\n");
      out.write("\n");
      out.write("<div class=\"Input\"> <!--id input div  -->\n");
      out.write("<input type=\"text\" id=\"id\" name=\"id\" class=\"idArea\" placeholder= \"아이디를 입력해주세요.\"> <br>\n");
      out.write("</div> <!--id input div 끝  -->\n");
      out.write("\n");
      out.write("<br><br>\n");
      out.write("\n");
      out.write("<p id=\"idMsg\" class=\"Msg\">영문, 숫자로 조합된 5~15자리여야 합니다.</p>\n");
      out.write("\n");
      out.write("</div> <!--id div끝  -->\n");
      out.write("\n");
      out.write("<!--==================== pw =======================  -->\n");
      out.write("<div class=\"Div\"> <!--pw div  -->\n");
      out.write("\n");
      out.write("<div class=\"pwText\"> <!--pw text  -->\n");
      out.write("비밀번호\n");
      out.write("</div> <!-- pw text 끝  -->\n");
      out.write("\n");
      out.write("<div class=\"pwInput\"> <!--pw input div  -->\n");
      out.write(" <input type=\"text\" id=\"pw\" name=\"pw\" class=\"pwArea\" placeholder= \"비밀번호를 입력해주세요.\" autocomplete=\"off\"> <br>\n");
      out.write("</div> <!--pw input div끝  -->\n");
      out.write("\n");
      out.write("<!-- 비번 사용 가능/불가능 여부  -->\n");
      out.write("<p id=\"pwMsg\" class=\"pwMsg\">영문, 숫자, 특수문자로 조합된 8~20자리여야 합니다. </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div> <!-- pw div 끝  -->\n");
      out.write("\n");
      out.write("<!--=================== pw check ==================  -->\n");
      out.write("<div class=\"Div\"> <!--pw check div  -->\n");
      out.write("비밀번호 재입력 : <input type=\"text\" id=\"pwCheck\" placeholder = \"비밀번호를 재입력해주세요.\" autocomplete=\"off\"> <br>\n");
      out.write("<!-- 비밀번호 일치 여부  -->\n");
      out.write("<p id=\"pwCheckMsg\"></p>\n");
      out.write("</div> <!--pw check div 끝  -->\n");
      out.write("\n");
      out.write("<div> <!--email div  -->\n");
      out.write("이메일 : <input type=\"text\" id=\"email\" name=\"email\" placeholder = \"이메일을 입력해주세요.\"> <button type=\"button\" id=\"emailCheckBtn\" disabled=\"disabled\">이메일인증</button> <br>\n");
      out.write("<p id=\"emailMsg\"></p>\n");
      out.write("<!--이메일 인증 여부  -->\n");
      out.write("</div> <!--email div끝  -->\n");
      out.write("\n");
      out.write("<div> <!--email check div  -->\n");
      out.write("인증번호 : <input type=\"text\" maxlength=\"7\" onkeyup=\"checkAuthNum()\" id=\"AuthNumInput\" disabled=\"disabled\" placeholder=\"인증번호를 입력하세요.\">\n");
      out.write("<p id=\"emailCheckMsg\"></p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div> <!--nickname div  -->\n");
      out.write("닉네임 : <input type=\"text\" id=\"nickname\" name=\"nickname\" placeholder = \"닉네임을 입력해주세요.\"> <br>\n");
      out.write("<!--사용가능한 닉네임 여부  -->\n");
      out.write("<p id=\"nicknameMsg\"></p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div> <!--birth div  -->\n");
      out.write("생년월일 : <input type=\"text\" name=\"birth\" placeholder = \"생년월일을 입력해주세요.\">\n");
      out.write("</div> <!--birth div 끝  -->\n");
      out.write("\n");
      out.write("<!-- 생년월일 : <button class=\"selectbox\" onclick=\"toggleListbox(event)\">년도<span class=\"material-symbols-outlined\">\n");
      out.write("stat_1</span></button>\n");
      out.write("		<ul class=\"listbox\" id=\"listbox\" size=\"5\" >\n");
      out.write("		   <li><button type=\"button\" class=\"list\">1950</button></li>\n");
      out.write("		   <li><button type=\"button\" class=\"list\">1951</button></li>\n");
      out.write("		</ul>  -->\n");
      out.write("		\n");
      out.write("\n");
      out.write("\n");
      out.write("<button type=\"submit\" id=\"signBtn\" disabled=\"disabled\">회원가입</button>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/userJoinJs.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
