/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-05 03:21:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userSearchPw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685707379948L));
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/_b66k/B66K/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TP_B66K/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/userSearchPw.css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"wrap\">\n");
      out.write("\n");
      out.write("<div class=\"findPwtextArea\">\n");
      out.write("	<p class=\"findPwText1\">비밀번호 찾기<p>	\n");
      out.write("	<hr id=\"line\">\n");
      out.write("	<div class=\"findPwText2\">\n");
      out.write("	<p class=\"findPwText3\">가입 시 입력한 이메일로 인증번호를 보내드립니다.<p>\n");
      out.write("   이메일을 입력하고 인증번호 받기를 누른 후 이메일로 온 인증번호를 입력해주세요. </div>\n");
      out.write("</div>\n");
      out.write("<form action=\"/member/searchPw\" method=\"post\">\n");
      out.write("\n");
      out.write("<div class=\"emailArea\">\n");
      out.write("\n");
      out.write("	<div class=\"emailInputArea\">\n");
      out.write("<input type=\"text\" name=\"email\" id=\"email\" placeholder=\"이메일을 입력해주세요.\" class=\"emailInput\">\n");
      out.write("<button type=\"button\" id=\"AuthNumBtn\" name=\"AuthNumBtn\" style=\"display: inline-block;\" class=\"SearchBtn\">인증번호 받기</button>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"emailAuthArea\">\n");
      out.write("\n");
      out.write("<input type=\"text\" id=\"emailCheckNum\" maxlength=\"7\" placeholder=\"인증번호를 입력해주세요.\" class=\"authInput\" \n");
      out.write("autocomplete=\"off\" style=\"display: none;\">\n");
      out.write("<!--style=\"display: none;\"  -->\n");
      out.write("<button type=\"button\" id=\"SearchPwBtn\" name=\"SearchPwBtn\" \n");
      out.write("class=\"SearchPwBtn\" style=\"display: none;\">인증번호 입력</button>\n");
      out.write("<!--style=\"display: none;\"  -->\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<!-- <a href=\"/member/searchId\"><button class=\"idSearchBtn\">아이디 찾기</button></a>\n");
      out.write("<a href=\"/\"><button class=\"homeBtn\">뒤로가기</button></a> -->\n");
      out.write("\n");
      out.write("<div class=\"btnArea\">\n");
      out.write("\n");
      out.write("  <a id=\"idSearchBtn\" class=\"idButton\" href=\"/member/searchId\">\n");
      out.write("  <span class=\"idSearchText\">아이디찾기</span>\n");
      out.write("  <span class=\"material-symbols-outlined search\">\n");
      out.write("	search\n");
      out.write("	</span>\n");
      out.write("  </a>\n");
      out.write("  \n");
      out.write("  <a id=\"homeBtn\" class=\"homeButton\" href=\"/\">\n");
      out.write("  <span class=\"homeText\">홈으로가기</span>\n");
      out.write("	<span class=\"material-symbols-outlined home\">\n");
      out.write("		arrow_back\n");
      out.write("	</span>\n");
      out.write("  </a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>  <!-- wrap div끝  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"searchPwPopup\" class=\"searchPwPopup\">\n");
      out.write("		<div class=\"searchPwPopup_content\">\n");
      out.write("			<div class=\"searchPwModalTitle\" id=\"searchPwModalTitle\">\n");
      out.write("					<div id=\"modalMessage\"></div>\n");
      out.write("				<div class=\"searchPwCloseBtn\">\n");
      out.write("				<p class=\"searchPwCloseText\">확인</p></div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/userSearchPw.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
